version: '3'

services:

    nbit_store_api:
        build:
            context: .
            dockerfile: Dockerfile
        command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
        ports:
            - "8000:8000"
        restart: always
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "10"
                labels: "todo-app"